
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: RafaelPereiraSantos/update-segment-functions@chore/add_logs
        with:
          authorization-token: my-secret-token